name: Job - RSSUpdateMain

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  job-rssupdate:
    runs-on: ubuntu-latest
    steps:
      - run: |
        curl "http://vanihutam.000webhostapp.com/feeds/services.php?source=github&do=RSSUpdate"
