name: Job - RSSBuild

on:
  workflow_dispatch:
  schedule:
    # 0 0 * * *
    - cron: '0 0 * * *'

jobs:
  job-rssbuild:
    runs-on: ubuntu-latest
    steps:
      - run: |
        curl "https://vanihutam.000webhostapp.com/feeds/export/?do=Build&MarkeRead=y"
