name: Job - RSSUpdate

on:
  workflow_dispatch:
  schedule:
    # */10 * * * *
    - cron: '*/10 * * * *'

jobs:
  job-rssupdate:
    runs-on: ubuntu-latest
    steps:
      - run: |
        curl --connect-timeout 60 -max-time 60 "http://vanihutam.000webhostapp.com/feeds/services.php?source=github&do=RSSUpdate"
