name: UpdateRSS

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: request url
        run: |
          curl 'http://vanihutam.000webhostapp.com/feeds/services.php?source=github&do=RSSUpdate'
